name: Daily Stock Reporter

on:
  schedule:
    # 這是 Cron 語法。台灣時間 10:30 = 減去 8 小時 = 國際標準時間 (UTC) 的 02:30
   - cron: '*/5 * * * *'
  workflow_dispatch: # 這個設定讓你可以隨時手動點擊「執行」來測試

jobs:
  run-stock-bot:
    runs-on: ubuntu-latest # 使用最新的 Linux 虛擬主機

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run stock script
      env: # 從保險箱把密碼拿出來給程式用
        TG_TOKEN: ${{ secrets.TG_TOKEN }}
        TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
      run: python stock_bot.py
