name: Daily Stock Reporter

on:
  schedule:
    # 這裡的設定代表：每週一到週五的 UTC 02:00 (台灣 10:00) 與 05:00 (台灣 13:00) 觸發
    - cron: '0 2,5 * * 1-5'
  workflow_dispatch:
jobs:
  run-stock-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run stock script
      env:
        TG_TOKEN: ${{ secrets.TG_TOKEN }}
        TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
      run: python stock_bot.py
